export const AUDIT_ACTIONS = Object.freeze({
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_DELETED: 'ORGANIZATION_DELETED',

  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  MEMBER_PERMISSIONS_UPDATED: 'MEMBER_PERMISSIONS_UPDATED',
  MEMBER_DISABLED: 'MEMBER_DISABLED',
  MEMBER_ENABLED: 'MEMBER_ENABLED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',

  INVITE_SENT: 'INVITE_SENT',
  INVITE_RESENT: 'INVITE_RESENT',
  INVITE_REVOKED: 'INVITE_REVOKED',
  INVITE_ACCEPTED: 'INVITE_ACCEPTED',

  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_DUPLICATED: 'EVENT_DUPLICATED',
  EVENT_DELETED: 'EVENT_DELETED',

  REGISTRATION_CREATED: 'REGISTRATION_CREATED',
  REGISTRATION_WAITLISTED: 'REGISTRATION_WAITLISTED',
  REGISTRATION_CANCELLED: 'REGISTRATION_CANCELLED',
  ATTENDANCE_MARKED: 'ATTENDANCE_MARKED',
});
