export const NOTIFICATION_TYPES = Object.freeze({
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  REGISTRATION_CONFIRMED: 'REGISTRATION_CONFIRMED',
  REGISTRATION_WAITLISTED: 'REGISTRATION_WAITLISTED',
  REGISTRATION_CANCELLED: 'REGISTRATION_CANCELLED',
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
});

export const NOTIFICATION_TYPE_VALUES = Object.values(NOTIFICATION_TYPES);
