export const ACTION_LABELS = {
  ORGANIZATION_CREATED: 'created the organization',
  ORGANIZATION_UPDATED: 'updated organization settings',
  ORGANIZATION_DELETED: 'deleted the organization',
  MEMBER_ROLE_CHANGED: "changed a member's role",
  MEMBER_PERMISSIONS_UPDATED: "updated a member's permissions",
  MEMBER_DISABLED: 'disabled a member',
  MEMBER_ENABLED: 'enabled a member',
  MEMBER_REMOVED: 'removed a member',
  INVITE_SENT: 'sent an invite',
  INVITE_RESENT: 'resent an invite',
  INVITE_REVOKED: 'revoked an invite',
  INVITE_ACCEPTED: 'accepted an invite',
  EVENT_CREATED: 'created an event',
  EVENT_UPDATED: 'updated an event',
  EVENT_PUBLISHED: 'published an event',
  EVENT_CANCELLED: 'cancelled an event',
  EVENT_DUPLICATED: 'duplicated an event',
  EVENT_DELETED: 'deleted an event',
  REGISTRATION_CREATED: 'registered for an event',
  REGISTRATION_WAITLISTED: 'joined a waitlist',
  REGISTRATION_CANCELLED: 'cancelled a registration',
  ATTENDANCE_MARKED: 'marked attendance',
};
