export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  ONBOARDING: '/onboarding',
  INVITE_ACCEPT: '/invites/accept',
  orgDashboard: (slug) => `/org/${slug}/dashboard`,
  orgMembers: (slug) => `/org/${slug}/members`,
  orgSettings: (slug) => `/org/${slug}/settings`,
  orgEvents: (slug) => `/org/${slug}/events`,
  orgEventNew: (slug) => `/org/${slug}/events/new`,
  orgEventDetail: (slug, eventId) => `/org/${slug}/events/${eventId}`,
  orgEventEdit: (slug, eventId) => `/org/${slug}/events/${eventId}/edit`,
  orgCalendar: (slug) => `/org/${slug}/calendar`,
  orgAnalytics: (slug) => `/org/${slug}/analytics`,
  orgAuditLogs: (slug) => `/org/${slug}/audit-logs`,
  orgNotifications: (slug) => `/org/${slug}/notifications`,
};

export const QUERY_KEYS = {
  CURRENT_USER: ['auth', 'me'],
  ORGANIZATION: (orgId) => ['organizations', orgId],
  MEMBERS: (orgId, filters) => ['organizations', orgId, 'members', filters],
  INVITES: (orgId, filters) => ['organizations', orgId, 'invites', filters],
  INVITE_PREVIEW: (token) => ['invites', token],
  EVENTS: (orgId, filters) => ['organizations', orgId, 'events', filters],
  EVENT: (eventId) => ['events', eventId],
  EVENT_REGISTRATIONS: (eventId, filters) => ['events', eventId, 'registrations', filters],
  MY_EVENTS: ['me', 'events'],
  ORG_ANALYTICS: (orgId) => ['organizations', orgId, 'analytics'],
  EVENT_ANALYTICS: (eventId) => ['events', eventId, 'analytics'],
  RECENT_ACTIVITY: (orgId, limit) => ['organizations', orgId, 'audit-logs', 'recent', limit],
  AUDIT_LOGS: (orgId, filters) => ['organizations', orgId, 'audit-logs', filters],
  MY_NOTIFICATIONS: (filters) => ['me', 'notifications', filters],
  UNREAD_NOTIFICATIONS_COUNT: ['me', 'notifications', 'unread-count'],
};
